# Generated by Django 5.0.1 on 2024-01-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_persistence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carta',
            old_name='attack',
            new_name='ataque',
        ),
    ]
