# Generated by Django 5.0.1 on 2024-01-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_persistence', '0002_rename_attack_carta_ataque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataque',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comportamento',
            name='nome',
            field=models.CharField(default='padrao', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(default='carne', max_length=200),
        ),
    ]
